apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rd0nrllr4-java-quarkus 
  janus-idp.io/tekton: rd0nrllr4-java-quarkus
  backstage.io/kubernetes-id: rd0nrllr4-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rd0nrllr4-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml